import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { cn } from "@/lib/utils";


const font = Open_Sans({subsets:['latin'],variable:'--font-open-sans'});


export const metadata: Metadata = {
  title: "Team Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", font.variable)}
    >
      <body className="min-h-full flex flex-col {font.className}">{children}</body>
    </html>
  );
}
